const Home = () => {
    return (
      <section>
        <h1>Site Esportivo</h1>
        
        <h2>
            Nosso site de esportes oferece uma cobertura completa sobre os eventos esportivos mais emocionantes do mundo. De futebol a basquete, de tênis a esportes radicais, aqui você encontra notícias, análises e atualizações em tempo real sobre suas equipes e atletas favoritos. Com uma equipe de jornalistas e especialistas, garantimos que você esteja sempre por dentro dos principais campeonatos e torneios, como a Copa do Mundo, a NBA, o Grand Slam de tênis e muito mais. Além das notícias, nosso site também oferece artigos exclusivos, entrevistas e vídeos de bastidores, para que você possa acompanhar tudo o que acontece no universo esportivo. A cada dia, trazemos conteúdo diversificado e interativo, proporcionando uma experiência única para todos os fãs de esporte. Se você ama esportes, este é o lugar ideal para estar.
            Nosso site de esportes oferece uma cobertura completa sobre os eventos esportivos mais emocionantes do mundo. De futebol a basquete, de tênis a esportes radicais, aqui você encontra notícias, análises e atualizações em tempo real sobre suas equipes e atletas favoritos. Com uma equipe de jornalistas e especialistas, garantimos que você esteja sempre por dentro dos principais campeonatos e torneios, como a Copa do Mundo, a NBA, o Grand Slam de tênis e muito mais. Além das notícias, nosso site também oferece artigos exclusivos, entrevistas e vídeos de bastidores, para que você possa acompanhar tudo o que acontece no universo esportivo. A cada dia, trazemos conteúdo diversificado e interativo, proporcionando uma experiência única para todos os fãs de esporte. Se você ama esportes, este é o lugar ideal para estar.
            Nosso site de esportes oferece uma cobertura completa sobre os eventos esportivos mais emocionantes do mundo. De futebol a basquete, de tênis a esportes radicais, aqui você encontra notícias, análises e atualizações em tempo real sobre suas equipes e atletas favoritos. Com uma equipe de jornalistas e especialistas, garantimos que você esteja sempre por dentro dos principais campeonatos e torneios, como a Copa do Mundo, a NBA, o Grand Slam de tênis e muito mais. Além das notícias, nosso site também oferece artigos exclusivos, entrevistas e vídeos de bastidores, para que você possa acompanhar tudo o que acontece no universo esportivo. A cada dia, trazemos conteúdo diversificado e interativo, proporcionando uma experiência única para todos os fãs de esporte. Se você ama esportes, este é o lugar ideal para estar.
            Nosso site de esportes oferece uma cobertura completa sobre os eventos esportivos mais emocionantes do mundo. De futebol a basquete, de tênis a esportes radicais, aqui você encontra notícias, análises e atualizações em tempo real sobre suas equipes e atletas favoritos. Com uma equipe de jornalistas e especialistas, garantimos que você esteja sempre por dentro dos principais campeonatos e torneios, como a Copa do Mundo, a NBA, o Grand Slam de tênis e muito mais. Além das notícias, nosso site também oferece artigos exclusivos, entrevistas e vídeos de bastidores, para que você possa acompanhar tudo o que acontece no universo esportivo. A cada dia, trazemos conteúdo diversificado e interativo, proporcionando uma experiência única para todos os fãs de esporte. Se você ama esportes, este é o lugar ideal para estar.
            Nosso site de esportes oferece uma cobertura completa sobre os eventos esportivos mais emocionantes do mundo. De futebol a basquete, de tênis a esportes radicais, aqui você encontra notícias, análises e atualizações em tempo real sobre suas equipes e atletas favoritos. Com uma equipe de jornalistas e especialistas, garantimos que você esteja sempre por dentro dos principais campeonatos e torneios, como a Copa do Mundo, a NBA, o Grand Slam de tênis e muito mais. Além das notícias, nosso site também oferece artigos exclusivos, entrevistas e vídeos de bastidores, para que você possa acompanhar tudo o que acontece no universo esportivo. A cada dia, trazemos conteúdo diversificado e interativo, proporcionando uma experiência única para todos os fãs de esporte. Se você ama esportes, este é o lugar ideal para estar.
            Nosso site de esportes oferece uma cobertura completa sobre os eventos esportivos mais emocionantes do mundo. De futebol a basquete, de tênis a esportes radicais, aqui você encontra notícias, análises e atualizações em tempo real sobre suas equipes e atletas favoritos. Com uma equipe de jornalistas e especialistas, garantimos que você esteja sempre por dentro dos principais campeonatos e torneios, como a Copa do Mundo, a NBA, o Grand Slam de tênis e muito mais. Além das notícias, nosso site também oferece artigos exclusivos, entrevistas e vídeos de bastidores, para que você possa acompanhar tudo o que acontece no universo esportivo. A cada dia, trazemos conteúdo diversificado e interativo, proporcionando uma experiência única para todos os fãs de esporte. Se você ama esportes, este é o lugar ideal para estar.
        </h2>
      </section>
    )
  }
  
  export default Home
  